apiVersion: grm.csye7125.local/v1alpha1
kind: GitHubReleasesMonitor
metadata:
  labels:
    app.kubernetes.io/name: cve-operator
    app.kubernetes.io/managed-by: kustomize
  name: githubreleasesmonitor-sample
spec:
  # Add fields here
  # "2006-01-02T15:04:05Z07:00"
  monitorFrom: "2024-08-01T05:00:00Z" 
  url: "https://api.github.com/repos/CVEProject/cvelistV5/releases"
